### ISSUE TITLE
Allow special characters in address mails

### ISSUE THREAD

**Issue by brcdpr** [tmlmt/bodegamap-collab#17]
Hello,

Awesome new project !! 🔥 🍺 

Please allow more special characters in address mails, such as '+' or '_'.
See: https://www.rfc-editor.org/rfc/rfc3696 (section 3)

Thanks.

**Comment by tmlmt** [comment]
Thank you so much @brcdpr !
I have not authorized everything from the RFC Standard but have added the + (which is a typical email delimiter), and the Danish special characters æ, å, ø. The underscore was already authorized.
